### PR TITLE
update 0.7.0

### PR DESCRIPTION
**Pull request by benoitm974**

### CODE REVIEW

**Comment by vulgo** [comment]
Thank you for this. A proposal for the next update.

1. Create branch ```next```
2. A commit renaming the ```OpenCore-*``` directory and removing OC blobs
3. The targeted OpenCore version is released
4. Committing the updated ```Docs``` directory (enabling ```Sample.plist``` diff)
5. Commit(s) for ```config.plist``` change(s)
6. Merge -> next
6. Add OC blobs
7. Commit removing kexts with updates
8. Add updated kexts
8. Merge -> main

**Comment by benoitm974** [comment]
Thanks for providing a list.
Also please note I think I might have broken the config on the booting since I get text boot and VGA definition at boot before os X boots up and get to native definition.
Benoit

**Comment by vulgo** [comment]
Update to latest binary ```Resources``` and set ```PickerVariant``` to ```Auto``` for working OpenCanopy.

VGA definition problem goes away switching ```TextRenderer``` to ```BuiltinGraphics```, but then the console becomes incredibly slow when only the fullscreen mode is implemented.

**Comment by benoitm974** [comment]
I'm still puzzle as my sound card no more works but I don't seem sto have changed anything from alc config ...

**Comment by vulgo** [comment]
Looking at your fork ```AppleALCU.kext``` is for ```ALC 408x``` USB audio codec present on recent motherboards only. Is ```AppleALC.kext``` installed and configured?

**Comment by benoitm974** [comment]
Well catch, thanks again !

**Comment by vulgo** [comment]
Closing this, feel free to request merging changes to ```config.plist``` into the ```next``` branch after OC 0.7.2 is released in August.

**Pull request closed without merging**
